export const categoryMap = {
  'Computer Science': [
    { shortName: 'cs.AI', longName: 'Artificial Intelligence' },
    { shortName: 'cs.AR', longName: 'Hardware Architecture' },
    { shortName: 'cs.CC', longName: 'Computational Complexity' },
    { shortName: 'cs.CE', longName: 'Computational Engineering, Finance, and Science' },
    { shortName: 'cs.CG', longName: 'Computational Geometry' },
    { shortName: 'cs.CL', longName: 'Computation and Language' },
    { shortName: 'cs.CR', longName: 'Cryptography and Security' },
    { shortName: 'cs.CV', longName: 'Computer Vision and Pattern Recognition' },
    { shortName: 'cs.CY', longName: 'Computers and Society' },
    { shortName: 'cs.DB', longName: 'Databases' },
    { shortName: 'cs.DC', longName: 'Distributed, Parallel, and Cluster Computing' },
    { shortName: 'cs.DL', longName: 'Digital Libraries' },
    { shortName: 'cs.DM', longName: 'Discrete Mathematics' },
    { shortName: 'cs.DS', longName: 'Data Structures and Algorithms' },
    { shortName: 'cs.ET', longName: 'Emerging Technologies' },
    { shortName: 'cs.FL', longName: 'Formal Languages and Automata Theory' },
    { shortName: 'cs.GL', longName: 'General Literature' },
    { shortName: 'cs.GR', longName: 'Graphics' },
    { shortName: 'cs.GT', longName: 'Computer Science and Game Theory' },
    { shortName: 'cs.HC', longName: 'Human-Computer Interaction' },
    { shortName: 'cs.IR', longName: 'Information Retrieval' },
    { shortName: 'cs.IT', longName: 'Information Theory' },
    { shortName: 'cs.LG', longName: 'Machine Learning' },
    { shortName: 'cs.LO', longName: 'Logic in Computer Science' },
    { shortName: 'cs.MA', longName: 'Multiagent Systems' },
    { shortName: 'cs.MM', longName: 'Multimedia' },
    { shortName: 'cs.MS', longName: 'Mathematical Software' },
    { shortName: 'cs.NA', longName: 'Numerical Analysis' },
    { shortName: 'cs.NE', longName: 'Neural and Evolutionary Computing' },
    { shortName: 'cs.NI', longName: 'Networking and Internet Architecture' },
    { shortName: 'cs.OH', longName: 'Other Computer Science' },
    { shortName: 'cs.OS', longName: 'Operating Systems' },
    { shortName: 'cs.PF', longName: 'Performance' },
    { shortName: 'cs.PL', longName: 'Programming Languages' },
    { shortName: 'cs.RO', longName: 'Robotics' },
    { shortName: 'cs.SC', longName: 'Symbolic Computation' },
    { shortName: 'cs.SD', longName: 'Sound' },
    { shortName: 'cs.SE', longName: 'Software Engineering' },
    { shortName: 'cs.SI', longName: 'Social and Information Networks' },
    { shortName: 'cs.SY', longName: 'Systems and Control' },
  ],
  Economics: [
    { shortName: 'econ.EM', longName: 'Econometrics' },
    { shortName: 'econ.GN', longName: 'General Economics' },
    { shortName: 'econ.TH', longName: 'Theoretical Economics' },
  ],
  'Electrical Engineering and Systems Science': [
    { shortName: 'eess.AS', longName: 'Audio and Speech Processing' },
    { shortName: 'eess.IV', longName: 'Image and Video Processing' },
    { shortName: 'eess.SP', longName: 'Signal Processing' },
    { shortName: 'eess.SY', longName: 'Systems and Control' },
  ],
  Mathematics: [
    { shortName: 'math.AC', longName: 'Commutative Algebra' },
    { shortName: 'math.AG', longName: 'Algebraic Geometry' },
    { shortName: 'math.AP', longName: 'Analysis of PDEs' },
    { shortName: 'math.AT', longName: 'Algebraic Topology' },
    { shortName: 'math.CA', longName: 'Classical Analysis and ODEs' },
    { shortName: 'math.CO', longName: 'Combinatorics' },
    { shortName: 'math.CT', longName: 'Category Theory' },
    { shortName: 'math.CV', longName: 'Complex Variables' },
    { shortName: 'math.DG', longName: 'Differential Geometry' },
    { shortName: 'math.DS', longName: 'Dynamical Systems' },
    { shortName: 'math.FA', longName: 'Functional Analysis' },
    { shortName: 'math.GM', longName: 'General Mathematics' },
    { shortName: 'math.GN', longName: 'General Topology' },
    { shortName: 'math.GR', longName: 'Group Theory' },
    { shortName: 'math.GT', longName: 'Geometric Topology' },
    { shortName: 'math.HO', longName: 'History and Overview' },
    { shortName: 'math.IT', longName: 'Information Theory' },
    { shortName: 'math.KT', longName: 'K-Theory and Homology' },
    { shortName: 'math.LO', longName: 'Logic' },
    { shortName: 'math.MG', longName: 'Metric Geometry' },
    { shortName: 'math.MP', longName: 'Mathematical Physics' },
    { shortName: 'math.NA', longName: 'Numerical Analysis' },
    { shortName: 'math.NT', longName: 'Number Theory' },
    { shortName: 'math.OA', longName: 'Operator Algebras' },
    { shortName: 'math.OC', longName: 'Optimization and Control' },
    { shortName: 'math.PR', longName: 'Probability' },
    { shortName: 'math.QA', longName: 'Quantum Algebra' },
    { shortName: 'math.RA', longName: 'Rings and Algebras' },
    { shortName: 'math.RT', longName: 'Representation Theory' },
    { shortName: 'math.SG', longName: 'Symplectic Geometry' },
    { shortName: 'math.SP', longName: 'Spectral Theory' },
    { shortName: 'math.ST', longName: 'Statistics Theory' },
  ],
  Physics: [
    { shortName: 'astro-ph.CO', longName: 'Cosmology and Nongalactic Astrophysics' },
    { shortName: 'astro-ph.EP', longName: 'Earth and Planetary Astrophysics' },
    { shortName: 'astro-ph.GA', longName: 'Astrophysics of Galaxies' },
    { shortName: 'astro-ph.HE', longName: 'High Energy Astrophysical Phenomena' },
    { shortName: 'astro-ph.IM', longName: 'Instrumentation and Methods for Astrophysics' },
    { shortName: 'astro-ph.SR', longName: 'Solar and Stellar Astrophysics' },
    { shortName: 'cond-mat.dis-nn', longName: 'Disordered Systems and Neural Networks' },
    { shortName: 'cond-mat.mes-hall', longName: 'Mesoscale and Nanoscale Physics' },
    { shortName: 'cond-mat.mtrl-sci', longName: 'Materials Science' },
    { shortName: 'cond-mat.other', longName: 'Other Condensed Matter' },
    { shortName: 'cond-mat.quant-gas', longName: 'Quantum Gases' },
    { shortName: 'cond-mat.soft', longName: 'Soft Condensed Matter' },
    { shortName: 'cond-mat.stat-mech', longName: 'Statistical Mechanics' },
    { shortName: 'cond-mat.str-el', longName: 'Strongly Correlated Electrons' },
    { shortName: 'cond-mat.supr-con', longName: 'Superconductivity' },
    { shortName: 'gr-qc', longName: 'General Relativity and Quantum Cosmology' },
    { shortName: 'hep-ex', longName: 'High Energy Physics - Experiment' },
    { shortName: 'hep-lat', longName: 'High Energy Physics - Lattice' },
    { shortName: 'hep-ph', longName: 'High Energy Physics - Phenomenology' },
    { shortName: 'hep-th', longName: 'High Energy Physics - Theory' },
    { shortName: 'math-ph', longName: 'Mathematical Physics' },
    { shortName: 'nlin.AO', longName: 'Adaptation and Self-Organizing Systems' },
    { shortName: 'nlin.CD', longName: 'Chaotic Dynamics' },
    { shortName: 'nlin.CG', longName: 'Cellular Automata and Lattice Gases' },
    { shortName: 'nlin.PS', longName: 'Pattern Formation and Solitons' },
    { shortName: 'nlin.SI', longName: 'Exactly Solvable and Integrable Systems' },
    { shortName: 'nucl-ex', longName: 'Nuclear Experiment' },
    { shortName: 'nucl-th', longName: 'Nuclear Theory' },
    { shortName: 'physics.acc-ph', longName: 'Accelerator Physics' },
    { shortName: 'physics.ao-ph', longName: 'Atmospheric and Oceanic Physics' },
    { shortName: 'physics.app-ph', longName: 'Applied Physics' },
    { shortName: 'physics.atm-clus', longName: 'Atomic and Molecular Clusters' },
    { shortName: 'physics.atom-ph', longName: 'Atomic Physics' },
    { shortName: 'physics.bio-ph', longName: 'Biological Physics' },
    { shortName: 'physics.chem-ph', longName: 'Chemical Physics' },
    { shortName: 'physics.class-ph', longName: 'Classical Physics' },
    { shortName: 'physics.comp-ph', longName: 'Computational Physics' },
    { shortName: 'physics.data-an', longName: 'Data Analysis, Statistics and Probability' },
    { shortName: 'physics.ed-ph', longName: 'Physics Education' },
    { shortName: 'physics.flu-dyn', longName: 'Fluid Dynamics' },
    { shortName: 'physics.gen-ph', longName: 'General Physics' },
    { shortName: 'physics.geo-ph', longName: 'Geophysics' },
    { shortName: 'physics.hist-ph', longName: 'History and Philosophy of Physics' },
    { shortName: 'physics.ins-det', longName: 'Instrumentation and Detectors' },
    { shortName: 'physics.med-ph', longName: 'Medical Physics' },
    { shortName: 'physics.optics', longName: 'Optics' },
    { shortName: 'physics.plasm-ph', longName: 'Plasma Physics' },
    { shortName: 'physics.pop-ph', longName: 'Popular Physics' },
    { shortName: 'physics.soc-ph', longName: 'Physics and Society' },
    { shortName: 'physics.space-ph', longName: 'Space Physics' },
    { shortName: 'quant-ph', longName: 'Quantum Physics' },
  ],
  'Quantitative Biology': [
    { shortName: 'q-bio.BM', longName: 'Biomolecules' },
    { shortName: 'q-bio.CB', longName: 'Cell Behavior' },
    { shortName: 'q-bio.GN', longName: 'Genomics' },
    { shortName: 'q-bio.MN', longName: 'Molecular Networks' },
    { shortName: 'q-bio.NC', longName: 'Neurons and Cognition' },
    { shortName: 'q-bio.OT', longName: 'Other Quantitative Biology' },
    { shortName: 'q-bio.PE', longName: 'Populations and Evolution' },
    { shortName: 'q-bio.QM', longName: 'Quantitative Methods' },
    { shortName: 'q-bio.SC', longName: 'Subcellular Processes' },
    { shortName: 'q-bio.TO', longName: 'Tissues and Organs' },
  ],
  'Quantitative Finance': [
    { shortName: 'q-fin.CP', longName: 'Computational Finance' },
    { shortName: 'q-fin.EC', longName: 'Economics' },
    { shortName: 'q-fin.GN', longName: 'General Finance' },
    { shortName: 'q-fin.MF', longName: 'Mathematical Finance' },
    { shortName: 'q-fin.PM', longName: 'Portfolio Management' },
    { shortName: 'q-fin.PR', longName: 'Pricing of Securities' },
    { shortName: 'q-fin.RM', longName: 'Risk Management' },
    { shortName: 'q-fin.ST', longName: 'Statistical Finance' },
    { shortName: 'q-fin.TR', longName: 'Trading and Market Microstructure' },
  ],
  Statistics: [
    { shortName: 'stat.AP', longName: 'Applications' },
    { shortName: 'stat.CO', longName: 'Computation' },
    { shortName: 'stat.ME', longName: 'Methodology' },
    { shortName: 'stat.ML', longName: 'Machine Learning' },
    { shortName: 'stat.OT', longName: 'Other Statistics' },
    { shortName: 'stat.TH', longName: 'Statistics Theory' },
  ],
};

type Category = {
  shortName: string;
  longName: string;
  group: string;
};

export const ungroupedCategories = Object.keys(categoryMap).reduce<Category[]>((acc, key) => {
  const elements = categoryMap[key as keyof typeof categoryMap].map((category) => ({ ...category, group: key }));
  return [...acc, ...elements];
}, []);

export const categoriesGroupedByShortName = Object.keys(categoryMap).reduce<Record<string, Category>>((acc, key) => {
  const elements = categoryMap[key as keyof typeof categoryMap];

  elements.forEach((element) => {
    acc[element.shortName] = { ...element, group: key };
  });

  return acc;
}, {});
