import React, { PropsWithChildren } from 'react';
import { Bot } from 'lucide-react';
import { CardSkeleton } from './card-skeleton';
import { cn } from '@/lib/utils';

type Props = {
  isLoading?: boolean;
  size?: 'small' | 'large';
};

export const SummaryPanel: React.FC<PropsWithChildren<Props>> = ({ children, isLoading, size = 'large' }) => {
  if (isLoading) {
    return <CardSkeleton />;
  }

  return (
    <div className="flex flex-col p-4 gap-2 bg-slate-100 rounded-lg">
      <h3
        className={cn('font-semibold', {
          'text-sm': size === 'small',
          'text-lg': size === 'large',
        })}>
        Summary
      </h3>
      <p>{children}</p>
      <div className="flex justify-end items-center gap-1 text-xs text-slate-500">
        @generated by <Bot width={20} height={20} />
      </div>
    </div>
  );
};
